apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: docker-registry
  namespace: default
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "200Gi"
  storageClassName: portworx-shared-gp3