- set_fact:
    qty: 2
  when: workers|length == 2
- set_fact:
    qty: 3
  when: workers|length > 2
- name: Create docker-registry pvc
  command: oc create -f /opt/installer/roles/cp4d_installer/files/docker-registry-pvc.yaml
  ignore_errors: yes
- name: Add registry-storage to registry deployment
  command: oc set volume -n default deploymentconfigs/docker-registry --add --name=registry-storage -t pvc --claim-name=docker-registry --overwrite
- name: patch deployments to {{qty}} for registry
  command: oc patch deploymentconfigs/docker-registry -n default -p '{"spec":{"replicas":{{qty}}}}'
- name: wait for registry pods
  shell: oc get pods -n default -l deploymentconfig=docker-registry --no-headers --field-selector=status.phase=Running | wc -l
  register: reg_cmd
  retries: 50
  delay: 15
  until: reg_cmd.stdout == "{{qty}}"
- name: extract docker registry
  command: oc get routes docker-registry -n default -o template=\{\{.spec.host}}
  register: docker_registry
- name: get token
  command: oc whoami -t
  register: oc_token
- name: run process-px-images
  command: |
    ./process-px-images.sh
    -r {{docker_registry.stdout}}
    -u ocadmin
    -p {{oc_token.stdout}}
    -s kube-system
    -d ./imgtemp
    -t ./px_2.5.0.1-dist.tgz
    -c podman
  environment:
    PODMAN_LOGIN_ARGS: --tls-verify=false
    PODMAN_PUSH_ARGS: --tls-verify=false
  args:
    chdir: /opt/cp4d/cpd-portworx/px-images