shared-services:
  kafka:
    volumeClaim:
      overrideStorageClass: true
      storageClassName: "portworx-kafka-sc"

wdp-db2:
  support4kDevice: true
  volumeClaim:
    storageClassName: "portworx-db2-rwo-sc"
    overrideStorageClass: true

xmetarepoVolumeInfo:
  support4kDevice: true
  volumeClaim:
    storageClassName: "portworx-db2-rwo-sc"
    overrideStorageClass: true