- name: run terraform init
  command: terraform init
- name: Run Terraform
  terraform:
    project_path: '{{playbook_dir}}'
    state: present
  register: terraform_outputs
- meta: refresh_inventory
