- name: load vars
  include_vars:
    dir: "{{playbook_dir}}/installer_files/group_vars"
- name: Disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager
- name: make sure devices are managed by NetworkManager
  ini_file:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: absent
    no_extra_spaces: yes
    option: NM_CONTROLLED
    section: null
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager
- name: make sure devices are managed by NetworkManager
  ini_file:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    state: absent
    no_extra_spaces: yes
    option: NM_CONTROLLED
    section: null
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager
- name: make sure hosts isn't overwritten on restart
  lineinfile:
    path: /etc/cloud/cloud.cfg
    line: "manage_etc_hosts: False"
    regexp: "^manage_etc_hosts"
- name: deploy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'
- name: deploy resolv.conf template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - reload NetworkManager
- name: Install Base Packages
  yum:
    name:
    - wget
    - git
    - net-tools
    - bind-utils
    - yum-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - docker-1.13.1
    state: present
  notify:
  - reboot machine
  ignore_errors: yes
- name: Gather the rpm package facts
  package_facts:
    manager: auto
- name: try to reinstall openshift-ansible
  include_tasks: openshift-ansible.yaml
  when: "'openshift-ansible' not in ansible_facts.packages"
- name: Update installed Packages
  yum:
    name: "*"
    state: latest
  notify:
  - reboot machine
- name: Making sure NetworkManager is started
  service:
    name: NetworkManager
    state: started
    enabled: yes
- name: Deploy systemctl configuration
  copy:
    src: 42-cp4d.conf
    dest: /etc/sysctl.d/42-cp4d.conf
- name: load sysctl
  command: sysctl -p /etc/sysctl.d/42-cp4d.conf